# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(default='', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
