# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='additional_image',
            field=models.TextField(null=True, verbose_name='Additonal Image'),
        ),
    ]
