# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160309_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='additional_image',
            field=models.TextField(blank=True, null=True, verbose_name='Additonal Image'),
        ),
    ]
